# Generated by Django 5.1.5 on 2025-01-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nycapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nycaddresslookuppage',
            name='header',
            field=models.CharField(default='NYC Address Lookup Tool', help_text='Header displayed at the top of the page.', max_length=255),
        ),
        migrations.AddField(
            model_name='nycaddresslookuppage',
            name='instructions',
            field=models.TextField(blank=True, default='Enter an address to retrieve NYC OpenData information, including 311 complaints, lead violations, bedbug reports, housing violations, and NYCHA data.', help_text='Instructions displayed to users on how to use the tool.'),
        ),
    ]
