# Generated by Django 5.1.5 on 2025-02-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nycapi', '0004_alter_nycaddresslookuppage_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nycaddresslookuppage',
            name='instructions',
            field=models.TextField(blank=True, default='Enter an address and zip code to retrieve NYC OpenData information, including 311 complaints, lead violations, bedbug reports, housing violations, and NYCHA data. A rent stabilized lookup is also provided.', help_text='Instructions displayed to users on how to use the tool.'),
        ),
    ]
