# Generated by Django 5.1.5 on 2025-02-16 16:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nycapi', '0006_nycaddresslookuppage_data_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='nycaddresslookuppage',
            name='how_to_use',
            field=wagtail.fields.RichTextField(blank=True, help_text='Instructions on how to use the page.'),
        ),
    ]
