# Generated by Django 5.1.5 on 2025-02-28 17:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nycapi', '0007_nycaddresslookuppage_how_to_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nycaddresslookuppage',
            name='header',
            field=wagtail.fields.RichTextField(default='NYC Address Lookup Tool', help_text='Header displayed at the top of the page.'),
        ),
    ]
