# Generated by Django 5.1.5 on 2025-02-28 17:51

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nycapi', '0008_alter_nycaddresslookuppage_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nycaddresslookuppage',
            name='header',
            field=models.TextField(default='NYC Address Lookup Tool', help_text='Header displayed at the top of the page.'),
        ),
        migrations.AlterField(
            model_name='nycaddresslookuppage',
            name='instructions',
            field=wagtail.fields.RichTextField(blank=True, default='Enter an address and zip code to retrieve NYC OpenData information, including 311 complaints, lead violations, bedbug reports, housing violations, and NYCHA data. A rent stabilized lookup is also provided.', help_text='Instructions displayed to users on how to use the tool.'),
        ),
    ]
