# Generated by Django 5.1.5 on 2025-02-28 18:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('nycapi', '0009_alter_nycaddresslookuppage_header_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HPDLookupPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('social_text', models.CharField(blank=True, max_length=255)),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.", max_length=255)),
                ('appear_in_search_results', models.BooleanField(default=True, help_text='Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.')),
                ('header', models.TextField(default='NYC HPD Lookup Tool', help_text='Header displayed at the top of the page.')),
                ('instructions', wagtail.fields.RichTextField(blank=True, default='Enter an address and zip code to scrape housing violation information directly from HPD Online. This tool will retrieve 311 complaints and housing violations by accessing the official HPD website.', help_text='Instructions displayed to users on how to use the tool.')),
                ('data_faqs', wagtail.fields.RichTextField(blank=True, help_text='Data FAQs content for the page.')),
                ('how_to_use', wagtail.fields.RichTextField(blank=True, help_text='Instructions on how to use the page.')),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
