# Generated by Django 5.1.11 on 2025-07-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nycapi', '0010_hpdlookuppage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nycaddresslookuppage',
            name='header',
            field=models.TextField(blank=True, default='', help_text='Header displayed at the top of the page.'),
        ),
    ]
