# Generated by Django 5.1.11 on 2025-07-05 19:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('images', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Subscriber's email address", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(blank=True, help_text="Subscriber's first name (optional)", max_length=100)),
                ('last_name', models.CharField(blank=True, help_text="Subscriber's last name (optional)", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscriber is currently subscribed')),
                ('subscribed_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the subscriber signed up')),
                ('unsubscribed_date', models.DateTimeField(blank=True, help_text='When the subscriber unsubscribed', null=True)),
                ('unsubscribe_token', models.CharField(blank=True, help_text='Unique token for unsubscribe links', max_length=64, null=True, unique=True)),
                ('source', models.CharField(default='website', help_text='Where the subscriber signed up from', max_length=100)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSignupPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('social_text', models.CharField(blank=True, max_length=255)),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.", max_length=255)),
                ('appear_in_search_results', models.BooleanField(default=True, help_text='Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introduction text displayed above the signup form')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, help_text='Text displayed after successful signup')),
                ('email_placeholder', models.CharField(default='Enter your email address', help_text='Placeholder text for email field', max_length=100)),
                ('first_name_placeholder', models.CharField(default='First name (optional)', help_text='Placeholder text for first name field', max_length=100)),
                ('last_name_placeholder', models.CharField(default='Last name (optional)', help_text='Placeholder text for last name field', max_length=100)),
                ('submit_button_text', models.CharField(default='Subscribe to Newsletter', help_text='Text for the submit button', max_length=50)),
                ('show_name_fields', models.BooleanField(default=True, help_text='Show first name and last name fields')),
                ('require_names', models.BooleanField(default=False, help_text='Make first name and last name required fields')),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'verbose_name': 'Newsletter Signup Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='NewsletterUnsubscribePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('social_text', models.CharField(blank=True, max_length=255)),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.", max_length=255)),
                ('appear_in_search_results', models.BooleanField(default=True, help_text='Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introduction text displayed on the unsubscribe page')),
                ('unsubscribe_success_text', wagtail.fields.RichTextField(blank=True, help_text='Text displayed after successful unsubscribe')),
                ('resubscribe_text', wagtail.fields.RichTextField(blank=True, help_text='Text displayed with resubscribe option')),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'verbose_name': 'Newsletter Unsubscribe Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
