# Generated by Django 5.1.11 on 2025-07-05 19:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_newslettersubscriber_newslettersignuppage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersignuppage',
            options={'verbose_name': 'Newsletter Page'},
        ),
        migrations.AddField(
            model_name='newslettersignuppage',
            name='resubscribe_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text displayed with resubscribe option'),
        ),
        migrations.AddField(
            model_name='newslettersignuppage',
            name='unsubscribe_success_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text displayed after successful unsubscribe'),
        ),
        migrations.DeleteModel(
            name='NewsletterUnsubscribePage',
        ),
    ]
