# Generated by Django 5.1.5 on 2025-02-09 19:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homedata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaltrendspage',
            name='faq_section',
            field=wagtail.fields.RichTextField(blank=True, help_text='FAQ content for the page (shown at the bottom).'),
        ),
    ]
