# Generated by Django 5.1.5 on 2025-02-16 16:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homedata', '0002_rentaltrendspage_faq_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaltrendspage',
            name='data_faqs',
            field=wagtail.fields.RichTextField(blank=True, help_text='Data FAQs content for the page.'),
        ),
    ]
