# Generated by Django 5.1.5 on 2025-02-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homedata', '0003_rentaltrendspage_data_faqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentaltrendspage',
            name='faq_section',
        ),
    ]
