# Generated by Django 5.1.5 on 2025-02-28 17:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homedata', '0005_rentaltrendspage_how_to_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaltrendspage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
