# Generated by Django 5.1.5 on 2025-02-28 17:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homedata', '0006_rentaltrendspage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaltrendspage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Intro text for the page.'),
        ),
    ]
