# Generated by Django 5.1.11 on 2025-07-12 16:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='footer_navigation',
            field=wagtail.fields.StreamField([('section', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'The heading for this section of links', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Internal Page'), ('external', 'External URL')], 'help_text': 'Choose whether this links to a page on this site or an external website'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Choose a page from this website', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter the full URL (e.g., https://example.com)', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'The text that will be displayed as the link', 'required': True}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Open this link in a new tab/window', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('link_type', 1), ('internal_page', 2), ('external_url', 3), ('title', 4), ('open_in_new_tab', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': 'Add links to this section', 'min_num': 0}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Internal Page'), ('external', 'External URL')], 'help_text': 'Choose whether this button links to a page on this site or an external website'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'The text that will be displayed on the button', 'required': True}), 10: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Open link in a new tab', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('link_type', 8), ('internal_page', 2), ('external_url', 3), ('text', 9), ('open_in_new_tab', 10)]], {'help_text': 'Add a prominent action button to this section (optional)', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('section_heading', 0), ('links', 7), ('action', 11)]], {})}, help_text='Organize footer links into sections with headings'),
        ),
    ]
