# Generated by Django 5.1.5 on 2025-04-20 14:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediasettings',
            options={'verbose_name': 'Social Media'},
        ),
        migrations.AlterModelOptions(
            name='systemmessagessettings',
            options={'verbose_name': 'System Messages'},
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='default_sharing_text',
            field=models.CharField(blank=True, help_text='Default text used when sharing pages on social media', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook_app_id',
            field=models.CharField(blank=True, help_text='Your Facebook App ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='Your Instagram handle without the @ symbol', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='linkedin_handle',
            field=models.CharField(blank=True, help_text='Your LinkedIn profile URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='tiktok_handle',
            field=models.CharField(blank=True, help_text='Your TikTok handle without the @ symbol', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Your Twitter/X handle without the @ symbol', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemmessagessettings',
            name='body_404',
            field=wagtail.fields.RichTextField(default='<p>The page you are looking for could not be found.</p>', help_text='Content shown on 404 pages'),
        ),
        migrations.AlterField(
            model_name='systemmessagessettings',
            name='footer_newsletter_signup_description',
            field=models.TextField(default='Get the latest updates and news delivered to your inbox.', help_text='Description for the newsletter signup section in the footer'),
        ),
        migrations.AlterField(
            model_name='systemmessagessettings',
            name='footer_newsletter_signup_link',
            field=models.URLField(default='', help_text='Link for the newsletter signup form', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemmessagessettings',
            name='footer_newsletter_signup_title',
            field=models.CharField(default='Stay Updated', help_text='Title for the newsletter signup section in the footer', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemmessagessettings',
            name='placeholder_image',
            field=models.ForeignKey(blank=True, help_text='Default image used when no image is specified', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='systemmessagessettings',
            name='title_404',
            field=models.CharField(default='Page not found', help_text='Title shown on 404 pages', max_length=255),
        ),
    ]
