# Generated by Django 5.1.5 on 2025-04-20 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('utils', '0002_alter_socialmediasettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmessagessettings',
            name='placeholder_image',
            field=models.ForeignKey(blank=True, help_text='Default image used when no image is specified', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
    ]
