# Generated by Django 5.1.11 on 2025-07-05 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_systemmessagessettings_placeholder_image'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdSenseSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_id', models.CharField(blank=True, help_text='Your Google AdSense Publisher ID (e.g., ca-pub-1234567890123456)', max_length=255)),
                ('ad_client', models.CharField(blank=True, help_text='Your Google AdSense Ad Client ID (e.g., ca-pub-1234567890123456)', max_length=255)),
                ('enable_adsense', models.BooleanField(default=False, help_text='Enable Google AdSense on the website')),
                ('header_ad_slot', models.CharField(blank=True, help_text='Ad slot ID for header ad (e.g., 1234567890)', max_length=255)),
                ('sidebar_ad_slot', models.CharField(blank=True, help_text='Ad slot ID for sidebar ad (e.g., 1234567890)', max_length=255)),
                ('content_ad_slot', models.CharField(blank=True, help_text='Ad slot ID for content area ad (e.g., 1234567890)', max_length=255)),
                ('footer_ad_slot', models.CharField(blank=True, help_text='Ad slot ID for footer ad (e.g., 1234567890)', max_length=255)),
                ('responsive_ad_slot', models.CharField(blank=True, help_text='Ad slot ID for responsive ad (e.g., 1234567890)', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Google AdSense',
            },
        ),
    ]
