# Generated by Django 5.1.11 on 2025-07-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_googleadsensesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleadsensesettings',
            name='ad_client',
        ),
        migrations.RemoveField(
            model_name='googleadsensesettings',
            name='content_ad_slot',
        ),
        migrations.RemoveField(
            model_name='googleadsensesettings',
            name='footer_ad_slot',
        ),
        migrations.RemoveField(
            model_name='googleadsensesettings',
            name='header_ad_slot',
        ),
        migrations.RemoveField(
            model_name='googleadsensesettings',
            name='responsive_ad_slot',
        ),
        migrations.RemoveField(
            model_name='googleadsensesettings',
            name='sidebar_ad_slot',
        ),
    ]
