# Generated by Django 5.1.11 on 2025-07-12 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('utils', '0005_remove_googleadsensesettings_ad_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessagessettings',
            name='apple_touch_icon',
            field=models.ForeignKey(blank=True, help_text='Apple touch icon for iOS devices (should be 180x180 pixels)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='systemmessagessettings',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Favicon for the website (should be square, recommended size: 32x32 or 64x64 pixels)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
    ]
