# Generated by Django 5.1.5 on 2025-08-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_remove_googleadsensesettings_ad_client_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentModeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_consent_mode', models.BooleanField(default=False, help_text='Enable Google Consent Mode v2 for EEA/UK traffic compliance')),
                ('google_tag_id', models.CharField(blank=True, help_text='Google Tag Manager ID (e.g., GTM-XXXXXXX) or Google Analytics 4 ID (e.g., G-XXXXXXXXXX)', max_length=255)),
                ('default_consent_state', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied')], default='denied', help_text='Default consent state for users outside EEA/UK', max_length=20)),
                ('enable_region_detection', models.BooleanField(default=True, help_text='Automatically detect EEA/UK users and apply appropriate consent settings')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Consent Mode Settings',
            },
        ),
    ]
