# Generated by Django 5.1.5 on 2025-08-14 16:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('standardpages', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('social_text', models.CharField(blank=True, max_length=255)),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.", max_length=255)),
                ('appear_in_search_results', models.BooleanField(default=True, help_text='Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.')),
                ('privacy_content', wagtail.fields.RichTextField(blank=True, help_text='Main privacy policy content including data collection, usage, and user rights')),
                ('cookie_policy', wagtail.fields.RichTextField(blank=True, help_text='Detailed information about cookies used on the site')),
                ('adsense_policy', wagtail.fields.RichTextField(blank=True, help_text='Information about Google AdSense, data sharing, and advertising')),
                ('user_choices', wagtail.fields.RichTextField(blank=True, help_text='Information about user choices, opt-out options, and data control')),
                ('contact_info', wagtail.fields.RichTextField(blank=True, help_text='Contact information for privacy-related inquiries')),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'verbose_name': 'Privacy Policy Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='TermsOfServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('social_text', models.CharField(blank=True, max_length=255)),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.", max_length=255)),
                ('appear_in_search_results', models.BooleanField(default=True, help_text='Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.')),
                ('terms_content', wagtail.fields.RichTextField(blank=True, help_text='Main terms of service content including usage rights and restrictions')),
                ('user_obligations', wagtail.fields.RichTextField(blank=True, help_text='User obligations and acceptable use policies')),
                ('intellectual_property', wagtail.fields.RichTextField(blank=True, help_text='Information about intellectual property rights and licensing')),
                ('liability', wagtail.fields.RichTextField(blank=True, help_text='Limitation of liability and disclaimers')),
                ('contact_info', wagtail.fields.RichTextField(blank=True, help_text='Contact information for terms-related inquiries')),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'verbose_name': 'Terms of Service Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
