# Generated by Django 5.1.5 on 2025-02-28 17:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='NYCAggregatedDashboardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header', models.CharField(default='NYC Aggregated Dashboard', help_text='Main heading for the dashboard page', max_length=255)),
                ('instructions', wagtail.fields.RichTextField(blank=True, help_text='Instructions on how to use the dashboard')),
            ],
            options={
                'verbose_name': 'NYC Aggregated Dashboard Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
