# Generated by Django 5.1.5 on 2025-04-20 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_nycaggregateddashboardpage'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='nycaggregateddashboardpage',
            name='appear_in_search_results',
            field=models.BooleanField(default=True, help_text='Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.'),
        ),
        migrations.AddField(
            model_name='nycaggregateddashboardpage',
            name='listing_image',
            field=models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='nycaggregateddashboardpage',
            name='listing_summary',
            field=models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.", max_length=255),
        ),
        migrations.AddField(
            model_name='nycaggregateddashboardpage',
            name='listing_title',
            field=models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255),
        ),
        migrations.AddField(
            model_name='nycaggregateddashboardpage',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='nycaggregateddashboardpage',
            name='social_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
