# Generated by Django 5.1.5 on 2025-08-10 17:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
